### ISSUE TITLE
Cannot find weights for CCN_Plastic

### ISSUE THREAD

**Issue by vaishali41** [zavalab/ML#5]
Hi, I cannot find the weights for CNN_Plastic on clicking the link in README.md. I do not have University of Wisconsin - Madison Box account and when I login using my Box account, I do not find the weights file. Can you please let me know where can I find the weights for the code? Thank you.

**Comment by iandownie07** [comment]
> Hi, I cannot find the weights for CNN_Plastic on clicking the link in README.md. I do not have University of Wisconsin - Madison Box account and when I login using my Box account, I do not find the weights file. Can you please let me know where can I find the weights for the code? Thank you.

Hi, vaishali41

Did you ever get the weights?

**Comment by sjiang87** [comment]
> Hi, sorry for the late reply. Can you please check this link?

https://uwmadison.box.com/s/bgo4vfac10gzgji43q4u1a9t1y6boba4

**Comment by igor-volgin** [comment]
Dear developer,

Thank you very much for this nice tool. However, the weights from the above link are not avaliable for downloading right now.  Could you please provide another link or upload them directly on github?

Thank you in advance.

Sincerely yours,
Igor

**Comment by dlcole3** [comment]
@sjiang87

**Comment by sjiang87** [comment]
Hi @igor-volgin, as I have changed institution and lost access to the Box folder.
But feel free to check the weights of more recent studies with the weights stored on Google Drive. They should be available.
https://github.com/zavalab/ML/tree/master/Plastic_FastIR
https://github.com/zavalab/ML/tree/master/Plastic_Rotating
