### ISSUE TITLE
Cannot find solvgnn_binary_final_model_cv.pth file

### ISSUE THREAD

**Issue by tom-mrt** [zavalab/ML#6]
I've tried running the notebook "Generate_Phase_Diagrams.ipynb", but when generate phase diagrams, I got an error "[Errno 2] No such file or directory: '../saved_model/solvgnn_binary_final_model_cv0.pth'".
Where can I find the file?

**Comment by Kenshikun** [comment]
I had the same issue as written by "tom-mrt". Please sharing the pth file for utilizing this great accomplishment for the real world simulation.

**Comment by AmyQ20** [comment]
File uploaded in 2023. Feel free to let me know if you have further issues.
